import { 
  UserAccount, 
  SekolahMitra, 
  LaporanBulanan, 
  Invoice, 
  Pembayaran, 
  EventItem, 
  PermintaanMitra, 
  StaffActivity, 
  AdminMitraStaff,
  TemplateDokumen, 
  PerformanceMenDAKI 
} from '../types';
import { HISTORICAL_TRANSACTIONS_SINCE_2022, processHistoricalDataToEntities } from './historicalSheetData';

const processedHistorical = processHistoricalDataToEntities(HISTORICAL_TRANSACTIONS_SINCE_2022);

export const INITIAL_ADMIN_STAFF: AdminMitraStaff[] = [
  {
    id: 'MO002',
    nama: 'Anita Sulastri',
    email: 'anita@lazuardi.sch.id',
    role: 'Kepala Bagian Mitra Office',
    telepon: '+62 812-3456-7890',
    status: 'Aktif',
  },
  {
    id: 'MO003',
    nama: 'Delfi Dwi Hermawati',
    email: 'delfi@lazuardi.sch.id',
    role: 'Officer',
    telepon: '+62 813-8899-1122',
    status: 'Aktif',
  },
];

export const INITIAL_USERS: UserAccount[] = [
  {
    userId: 'admin',
    nama: 'Administrator Mitra Office',
    email: 'admin@lazuardi.sch.id',
    password: 'admin123',
    role: 'Administrator',
    akses: 'Full Akses',
    status: 'Aktif',
  },
  {
    userId: 'MO002',
    nama: 'Anita Sulastri',
    email: 'anita@lazuardi.sch.id',
    password: 'admin123',
    role: 'Kepala Bagian Mitra Office',
    akses: 'Full Akses',
    status: 'Aktif',
  },
  {
    userId: 'MO003',
    nama: 'Delfi Dwi Hermawati',
    email: 'delfi@lazuardi.sch.id',
    password: 'admin123',
    role: 'Officer',
    akses: 'Full Akses',
    status: 'Aktif',
  },
  {
    userId: 'MO004',
    nama: 'Lazuardi Al Falah Depok',
    email: 'alfalah.depok@lazuardi.sch.id',
    password: 'admin123',
    role: 'Sekolah Mitra',
    akses: 'Akses Terbatas',
    status: 'Aktif',
    sekolahId: 'MO004',
  },
  {
    userId: 'MO005',
    nama: 'Lazuardi Al Falah Klaten',
    email: 'alfalah.klaten@lazuardi.sch.id',
    password: 'admin123',
    role: 'Sekolah Mitra',
    akses: 'Akses Terbatas',
    status: 'Aktif',
    sekolahId: 'MO005',
  },
  {
    userId: 'MO013',
    nama: 'Lazuardi Athaillah',
    email: 'athaillah.makassar@lazuardi.sch.id',
    password: 'admin123',
    role: 'Sekolah Afiliasi',
    akses: 'Akses Terbatas',
    status: 'Aktif',
    sekolahId: 'MO013',
  },
  {
    userId: 'MO006',
    nama: 'Lazuardi Cordova',
    email: 'cordova@lazuardi.sch.id',
    password: 'admin123',
    role: 'Sekolah Mitra',
    akses: 'Akses Terbatas',
    status: 'Aktif',
    sekolahId: 'MO006',
  },
  {
    userId: 'MO007',
    nama: 'Lazuardi Haura',
    email: 'haura@lazuardi.sch.id',
    password: 'admin123',
    role: 'Sekolah Mitra',
    akses: 'Akses Terbatas',
    status: 'Aktif',
    sekolahId: 'MO007',
  },
  {
    userId: 'MO008',
    nama: 'Lazuardi Ibnu Sina',
    email: 'ibnusina@lazuardi.sch.id',
    password: 'admin123',
    role: 'Sekolah Mitra',
    akses: 'Akses Terbatas',
    status: 'Aktif',
    sekolahId: 'MO008',
  },
  {
    userId: 'MO009',
    nama: 'Lazuardi Ideal',
    email: 'ideal@lazuardi.sch.id',
    password: 'admin123',
    role: 'Sekolah Mitra',
    akses: 'Akses Terbatas',
    status: 'Aktif',
    sekolahId: 'MO009',
  },
  {
    userId: 'MO011',
    nama: 'SMA Lazuardi',
    email: 'sma.lazuardi@lazuardi.sch.id',
    password: 'admin123',
    role: 'Sekolah Afiliasi',
    akses: 'Akses Terbatas',
    status: 'Aktif',
    sekolahId: 'MO011',
  },
  {
    userId: 'MO010',
    nama: 'Lazuardi Kamila',
    email: 'kamila.solo@lazuardi.sch.id',
    password: 'admin123',
    role: 'Sekolah Afiliasi',
    akses: 'Akses Terbatas',
    status: 'Aktif',
    sekolahId: 'MO010',
  },
  {
    userId: 'MO012',
    nama: 'Lazuardi Tursina',
    email: 'tursina@lazuardi.sch.id',
    password: 'admin123',
    role: 'Sekolah Mitra',
    akses: 'Akses Terbatas',
    status: 'Aktif',
    sekolahId: 'MO012',
  },
];

export const INITIAL_SEKOLAH: SekolahMitra[] = [
  {
    id: 'MO004',
    kodeMitra: 'MO004',
    namaSekolah: 'Lazuardi Al Falah Depok',
    alamat: 'Jl. Raya Radar AURI No. 12, Cisalak Pasar, Cimanggis',
    kota: 'Depok',
    pimpinan: 'Ust. H. Rahmat Hidayat, M.Pd.',
    kontak: '021-8745912',
    email: 'alfalah.depok@lazuardi.sch.id',
    jenjang: 'SD, SMP',
    jumlahSiswa: 380,
    statusKerjasama: 'Aktif',
    kategoriSekolah: 'Mitra Reguler',
    tahunBergabung: 2018,
  },
  {
    id: 'MO005',
    kodeMitra: 'MO005',
    namaSekolah: 'Lazuardi Al Falah Klaten',
    alamat: 'Jl. Pemuda No. 88, Tonggalan, Klaten Tengah',
    kota: 'Klaten',
    pimpinan: 'Ibu Siti Nurhaliza, M.Pd.',
    kontak: '0272-321940',
    email: 'alfalah.klaten@lazuardi.sch.id',
    jenjang: 'Pra-TK, TK, SD',
    jumlahSiswa: 240,
    statusKerjasama: 'Aktif',
    kategoriSekolah: 'Mitra Reguler',
    tahunBergabung: 2020,
  },
  {
    id: 'MO013',
    kodeMitra: 'MO013',
    namaSekolah: 'Lazuardi Athaillah',
    alamat: 'Jl. Hertasning Baru No. 88, Kassi-Kassi, Rappocini',
    kota: 'Makassar',
    pimpinan: 'Dr. H. Muhammad Arifin, M.Pd.',
    kontak: '0411-8982341',
    email: 'athaillah.makassar@lazuardi.sch.id',
    jenjang: 'Pra-TK, TK, SD, SMP',
    jumlahSiswa: 290,
    statusKerjasama: 'Afiliasi',
    kategoriSekolah: 'Sekolah Afiliasi',
    tahunBergabung: 2022,
    keteranganKhusus: 'Sekolah Mitra (2022–2024), beralih menjadi Sekolah Afiliasi sejak Juli 2024 (bebas kewajiban pembayaran, hanya pelaporan tagihan)',
  },
  {
    id: 'MO006',
    kodeMitra: 'MO006',
    namaSekolah: 'Lazuardi Cordova',
    alamat: 'Komp. Banjar Wijaya Blok B5, Cipete, Pinang',
    kota: 'Tangerang',
    pimpinan: 'Bpk. Irwan Setiawan, S.Pd.',
    kontak: '021-5579883',
    email: 'cordova@lazuardi.sch.id',
    jenjang: 'Pra-TK, TK, SD',
    jumlahSiswa: 310,
    statusKerjasama: 'Aktif',
    kategoriSekolah: 'Mitra Reguler',
    tahunBergabung: 2016,
  },
  {
    id: 'MO007',
    kodeMitra: 'MO007',
    namaSekolah: 'Lazuardi Haura',
    alamat: 'Jl. Raya Pajajaran No. 45, Baranangsiang',
    kota: 'Bogor',
    pimpinan: 'Ibu Dra. Mardiana',
    kontak: '0251-831490',
    email: 'haura@lazuardi.sch.id',
    jenjang: 'TK, SD',
    jumlahSiswa: 195,
    statusKerjasama: 'Aktif',
    kategoriSekolah: 'Mitra Reguler',
    tahunBergabung: 2021,
  },
  {
    id: 'MO008',
    kodeMitra: 'MO008',
    namaSekolah: 'Lazuardi Ibnu Sina',
    alamat: 'Jl. Raden Inten II No. 102, Duren Sawit',
    kota: 'Jakarta Timur',
    pimpinan: 'Ust. Drs. Ahmad Fauzi, M.M.',
    kontak: '021-8611029',
    email: 'ibnusina@lazuardi.sch.id',
    jenjang: 'TK, SD, SMP',
    jumlahSiswa: 420,
    statusKerjasama: 'Aktif',
    kategoriSekolah: 'Mitra Reguler',
    tahunBergabung: 2015,
  },
  {
    id: 'MO009',
    kodeMitra: 'MO009',
    namaSekolah: 'Lazuardi Ideal',
    alamat: 'Kawasan EduTown Blok A3, BSD City, Serpong',
    kota: 'Tangerang Selatan',
    pimpinan: 'Ibu Hj. Nurbaeti, M.Pd.',
    kontak: '021-7569102',
    email: 'ideal@lazuardi.sch.id',
    jenjang: 'Pra-TK, TK, SD',
    jumlahSiswa: 210,
    statusKerjasama: 'Aktif',
    kategoriSekolah: 'Mitra Reguler',
    tahunBergabung: 2022,
  },
  {
    id: 'MO011',
    kodeMitra: 'MO011',
    namaSekolah: 'SMA Lazuardi',
    alamat: 'Jl. Cinere Raya No. 19, Cinere',
    kota: 'Depok',
    pimpinan: 'Bpk. Sonny J. Maulana, M.Si.',
    kontak: '021-7548901',
    email: 'sma.lazuardi@lazuardi.sch.id',
    jenjang: 'SMA',
    jumlahSiswa: 260,
    statusKerjasama: 'Afiliasi',
    kategoriSekolah: 'Khusus Pelaporan',
    tahunBergabung: 2014,
    keteranganKhusus: 'Pelaporan tagihan saja, tidak memiliki kewajiban pembayaran',
  },
  {
    id: 'MO010',
    kodeMitra: 'MO010',
    namaSekolah: 'Lazuardi Kamila',
    alamat: 'Jl. Dr. Wahidin No. 27, Penumping, Laweyan',
    kota: 'Solo',
    pimpinan: 'Bpk. Dr. H. Mulyono',
    kontak: '0271-714522',
    email: 'kamila.solo@lazuardi.sch.id',
    jenjang: 'TK, SD',
    jumlahSiswa: 185,
    statusKerjasama: 'Afiliasi',
    kategoriSekolah: 'Khusus Pelaporan',
    tahunBergabung: 2023,
    keteranganKhusus: 'Pelaporan tagihan saja, tidak memiliki kewajiban pembayaran',
  },
  {
    id: 'MO012',
    kodeMitra: 'MO012',
    namaSekolah: 'Lazuardi Tursina',
    alamat: 'Jl. Terusan Buah Batu No. 204, Batununggal',
    kota: 'Bandung',
    pimpinan: 'Ibu Dra. Hj. Ratna Juwita',
    kontak: '022-7561930',
    email: 'tursina@lazuardi.sch.id',
    jenjang: 'SD, SMP',
    jumlahSiswa: 340,
    statusKerjasama: 'Aktif',
    kategoriSekolah: 'Mitra Reguler',
    tahunBergabung: 2019,
  },
];

export const INITIAL_LAPORAN: LaporanBulanan[] = [
  {
    id: 'LAP-2026-09-001',
    mitraId: 'MO004',
    namaSekolah: 'Al-Falah Depok',
    bulan: 'Agustus',
    tahun: 2026,
    tahunAjaran: '2026/2027',
    tanggalKirim: '2026-09-02',
    kategori: 'Komprehensif',
    ringkasan: 'Pelaksanaan asesmen diagnostik awal semester berjalan lancar. Kehadiran siswa 98.4%. Sebanyak 3 event internal berhasil dilaksanakan.',
    kendala: 'Kebutuhan modul tambahan kurikulum Cambridge untuk jenjang SMP grade 7.',
    solusi: 'Mengajukan pemesanan dokumen cetak & modul via L-MAP ke Mitra Office.',
    linkDokumen: 'https://docs.google.com/document/d/1lazuardi-report-alfalah-depok/edit',
    status: 'Diterima',
    catatanAdmin: 'Laporan sangat rapi dan komprehensif. Modul Cambridge sedang dipersiapkan Mitra Office.',
    tanggalDiajukan: '2026-09-02',
    sheetPerhitungan: {
      namaSheet: 'Rekap Keuangan & Operasional Agustus 2026',
      namaFile: 'rekap_alfalah_agustus_2026.csv',
      tanggalUpload: '2026-09-02',
      rows: [
        {
          id: 'R01',
          kode: 'IN-01',
          deskripsi: 'Penerimaan SPP Reguler Siswa SD (Grade 1 - 6)',
          kategori: 'Pemasukan',
          volume: 245,
          satuan: 'Siswa',
          tarifSatuan: 1250000,
          totalHitungan: 306250000,
          totalTercatat: 306250000,
          selisih: 0,
          statusAudit: 'Sesuai',
        },
        {
          id: 'R02',
          kode: 'IN-02',
          deskripsi: 'Penerimaan SPP Siswa Inklusi / IEP',
          kategori: 'Pemasukan',
          volume: 18,
          satuan: 'Siswa',
          tarifSatuan: 2200000,
          totalHitungan: 39600000,
          totalTercatat: 39600000,
          selisih: 0,
          statusAudit: 'Sesuai',
        },
        {
          id: 'R03',
          kode: 'OUT-01',
          deskripsi: 'Honorarium Guru & Shadow Teacher Bulan Agustus',
          kategori: 'Pengeluaran',
          volume: 32,
          satuan: 'Staff',
          tarifSatuan: 4500000,
          totalHitungan: 144000000,
          totalTercatat: 144000000,
          selisih: 0,
          statusAudit: 'Sesuai',
        },
        {
          id: 'R04',
          kode: 'OUT-02',
          deskripsi: 'Operasional Pembelajaran & Modul Kurikulum MenDAKI',
          kategori: 'Pengeluaran',
          volume: 263,
          satuan: 'Paket',
          tarifSatuan: 150000,
          totalHitungan: 39450000,
          totalTercatat: 39450000,
          selisih: 0,
          statusAudit: 'Sesuai',
        },
      ],
      totalPemasukan: 345850000,
      totalPengeluaran: 183450000,
      saldoBersih: 162400000,
      totalSelisihDitemukan: 0,
      statusPerbaikan: 'Sesuai / Valid',
      catatanAudit: ['Semua formula perkalian volume × tarif dan total saldo diverifikasi akurat.'],
    },
  },
  {
    id: 'LAP-2026-08-001',
    mitraId: 'MO004',
    namaSekolah: 'Al-Falah Depok',
    bulan: 'Juli',
    tahun: 2026,
    tahunAjaran: '2026/2027',
    tanggalKirim: '2026-08-03',
    kategori: 'Komprehensif',
    ringkasan: 'Pembukaan tahun ajaran baru, MPLS ramah anak inklusif, dan sosialisasi nilai compassionate culture kepada seluruh wali murid.',
    kendala: 'Adaptasi awal beberapa siswa berkebutuhan khusus baru.',
    solusi: 'Pendampingan intensif bersama shadow teacher dan psikolog sekolah.',
    linkDokumen: 'https://docs.google.com/document/d/1lazuardi-alfalah-juli-2026/edit',
    status: 'Diterima',
    catatanAdmin: 'Kegiatan MPLS terdokumentasi dengan sangat baik.',
    tanggalDiajukan: '2026-08-03',
  },
  {
    id: 'LAP-2026-09-005',
    mitraId: 'MO004',
    namaSekolah: 'Al-Falah Depok',
    bulan: 'September',
    tahun: 2026,
    tahunAjaran: '2026/2027',
    tanggalKirim: '2026-09-15',
    kategori: 'Akademik',
    ringkasan: 'Persiapan pelaksanaan Penilaian Tengah Semester (PTS) dan workshop kurikulum tematik terpadu.',
    kendala: 'Jadwal supervisi bertepatan dengan agenda akreditasi.',
    solusi: 'Penjadwalan ulang supervisi bersama tim Mitra Office.',
    linkDokumen: 'https://docs.google.com/document/d/1lazuardi-alfalah-september-2026/edit',
    status: 'Diajukan',
    tanggalDiajukan: '2026-09-15',
  },
  {
    id: 'LAP-2026-09-002',
    mitraId: 'MO006',
    namaSekolah: 'Cordova',
    bulan: 'Agustus',
    tahun: 2026,
    tahunAjaran: '2026/2027',
    tanggalKirim: '2026-09-05',
    kategori: 'Akademik',
    ringkasan: 'Implementasi program Inklusi Ramah Anak dan Compassionate Day perayaan bulan kemerdekaan dengan keterlibatan komite sekolah.',
    kendala: 'Rotasi 2 guru kelas SD memerlukan orientasi modul Lazuardi baru.',
    solusi: 'Mengikutsertakan guru pada webinar supervisi akademik pekan depan.',
    linkDokumen: 'https://docs.google.com/document/d/1lazuardi-report-cordova/edit',
    status: 'Direview',
    catatanAdmin: 'Sedang direview oleh Officer Delfi Dwi Hermawati.',
    tanggalDiajukan: '2026-09-05',
  },
  {
    id: 'LAP-2026-08-002',
    mitraId: 'MO006',
    namaSekolah: 'Cordova',
    bulan: 'Juli',
    tahun: 2026,
    tahunAjaran: '2026/2027',
    tanggalKirim: '2026-08-05',
    kategori: 'Komprehensif',
    ringkasan: 'Kesiapan sarana pembelajaran, orientasi siswa baru pra-TK hingga SD, dan pengadaan buku panduan kurikulum.',
    kendala: 'Pengiriman seragam tambahan dari vendor sempat tertunda.',
    solusi: 'Dikoordinasikan langsung ke bagian logistik Mitra Office.',
    linkDokumen: 'https://docs.google.com/document/d/1lazuardi-cordova-juli-2026/edit',
    status: 'Diterima',
    catatanAdmin: 'Dokumen lengkap dan terverifikasi.',
    tanggalDiajukan: '2026-08-05',
  },
  {
    id: 'LAP-2026-09-003',
    mitraId: 'MO008',
    namaSekolah: 'Ibnu Sina',
    bulan: 'Agustus',
    tahun: 2026,
    tahunAjaran: '2026/2027',
    tanggalKirim: '2026-09-10',
    kategori: 'Keuangan',
    ringkasan: 'Laporan cashflow bulanan dan realisasi anggaran fasilitas laboratorium IPA.',
    kendala: 'Terdapat selisih pencatatan piutang termin seragam dengan distributor lokal.',
    solusi: 'Menyeragamkan format rekonsiliasi dengan Mitra Office.',
    linkDokumen: 'https://docs.google.com/spreadsheets/d/1lazuardi-keuangan-ibnusina/edit',
    status: 'Diajukan',
    tanggalDiajukan: '2026-09-10',
    sheetPerhitungan: {
      namaSheet: 'Sheet Audit Anggaran Laboratorium & SPP Ibnu Sina',
      namaFile: 'sheet_anggaran_ibnusina_upload.csv',
      tanggalUpload: '2026-09-10',
      rows: [
        {
          id: 'R01',
          kode: 'IN-01',
          deskripsi: 'Penerimaan SPP Siswa SMP Ibnu Sina',
          kategori: 'Pemasukan',
          volume: 180,
          satuan: 'Siswa',
          tarifSatuan: 1400000,
          totalHitungan: 252000000,
          totalTercatat: 242000000,
          selisih: 10000000,
          statusAudit: 'Selisih Perhitungan',
          catatanKoreksi: 'Tercatat Rp 242.000.000, seharusnya 180 × 1.400.000 = Rp 252.000.000 (Selisih +Rp 10.000.000)',
        },
        {
          id: 'R02',
          kode: 'IN-02',
          deskripsi: 'Subsidi Praktikum & Ekskul Robotik',
          kategori: 'Pemasukan',
          volume: 45,
          satuan: 'Siswa',
          tarifSatuan: 300000,
          totalHitungan: 13500000,
          totalTercatat: 13500000,
          selisih: 0,
          statusAudit: 'Sesuai',
        },
        {
          id: 'R03',
          kode: 'OUT-01',
          deskripsi: 'Pengadaan Kit Mikroskop & Reagen Lab IPA',
          kategori: 'Pengeluaran',
          volume: 15,
          satuan: 'Set',
          tarifSatuan: 2800000,
          totalHitungan: 42000000,
          totalTercatat: 46000000,
          selisih: -4000000,
          statusAudit: 'Selisih Perhitungan',
          catatanKoreksi: 'Tercatat Rp 46.000.000, seharusnya 15 × 2.800.000 = Rp 42.000.000 (Selisih -Rp 4.000.000)',
        },
        {
          id: 'R04',
          kode: 'OUT-02',
          deskripsi: 'Instalasi Meja Uji Asam & Ventilasi Lab',
          kategori: 'Pengeluaran',
          volume: 4,
          satuan: 'Unit',
          tarifSatuan: 4500000,
          totalHitungan: 18000000,
          totalTercatat: 18000000,
          selisih: 0,
          statusAudit: 'Sesuai',
        },
      ],
      totalPemasukan: 265500000,
      totalPengeluaran: 60000000,
      saldoBersih: 205500000,
      totalSelisihDitemukan: 14000000,
      statusPerbaikan: 'Ada Selisih',
      catatanAudit: [
        'Ditemukan 2 baris selisih perkalian volume × tarif pada file upload.',
        'Klik tombol "Perbaiki Otomatis" untuk mengoreksi angka dan menyeimbangkan saldo kas.'
      ],
    },
  },
  {
    id: 'LAP-2026-08-003',
    mitraId: 'MO008',
    namaSekolah: 'Ibnu Sina',
    bulan: 'Juli',
    tahun: 2026,
    tahunAjaran: '2026/2027',
    tanggalKirim: '2026-08-08',
    kategori: 'Komprehensif',
    ringkasan: 'Laporan pembukaan tahun ajaran baru, daftar siswa teregistrasi ulang, dan rancangan program tahfidz.',
    kendala: 'Tidak ada kendala operasional.',
    solusi: 'Program terlaksana sesuai roadmap.',
    linkDokumen: 'https://docs.google.com/document/d/1lazuardi-ibnusina-juli-2026/edit',
    status: 'Diterima',
    catatanAdmin: 'Disetujui. Lanjutkan persiapan audit laboratorium.',
    tanggalDiajukan: '2026-08-08',
  },
  {
    id: 'LAP-2026-09-004',
    mitraId: 'MO005',
    namaSekolah: 'Al-Falah Klaten',
    bulan: 'Juli',
    tahun: 2026,
    tahunAjaran: '2026/2027',
    tanggalKirim: '2026-08-01',
    kategori: 'SDM & Operasional',
    ringkasan: 'Laporan evaluasi orientasi guru baru dan kesiapan tahun ajaran 2026/2027.',
    kendala: 'Dokumentasi bukti pelatihan guru belum lengkap terlampir pada Google Drive.',
    solusi: 'Diminta melampirkan daftar hadir dan sertifikat pelatihan internal.',
    linkDokumen: 'https://docs.google.com/document/d/1lazuardi-report-klaten/edit',
    status: 'Perlu Revisi',
    catatanAdmin: 'Mohon update link folder bukti absensi dan foto kegiatan sebelum 20 September 2026.',
    tanggalDiajukan: '2026-08-01',
  },
  {
    id: 'LAP-2026-08-004',
    mitraId: 'MO011',
    namaSekolah: 'SMA Lazuardi',
    bulan: 'Juli',
    tahun: 2026,
    tahunAjaran: '2026/2027',
    tanggalKirim: '2026-08-02',
    kategori: 'Komprehensif',
    ringkasan: 'Laporan kesiapan pembelajaran berbasis riset (Research-Based Learning) dan integrasi kurikulum global IB/Cambridge grade 10.',
    kendala: 'Sinkronisasi jadwal mentor eksternal proyek penelitian siswa.',
    solusi: 'Mitra Office memfasilitasi kontak narasumber institusi mitra.',
    linkDokumen: 'https://docs.google.com/document/d/1lazuardi-sma-juli-2026/edit',
    status: 'Diterima',
    catatanAdmin: 'Sangat baik. Program riset mandiri berjalan sesuai target kurikulum.',
    tanggalDiajukan: '2026-08-02',
  },
  {
    id: 'LAP-2026-09-006',
    mitraId: 'MO011',
    namaSekolah: 'SMA Lazuardi',
    bulan: 'Agustus',
    tahun: 2026,
    tahunAjaran: '2026/2027',
    tanggalKirim: '2026-09-01',
    kategori: 'Akademik',
    ringkasan: 'Laporan pelaksanaan simulasi model United Nations (MUN) internal dan evaluasi portofolio literasi siswa.',
    kendala: 'Kebutuhan ruang pameran karya seni dan sains.',
    solusi: 'Optimalisasi selasar serbaguna dan galeri digital.',
    linkDokumen: 'https://docs.google.com/document/d/1lazuardi-sma-agustus-2026/edit',
    status: 'Diterima',
    catatanAdmin: 'Laporan tepat waktu dan rapi.',
    tanggalDiajukan: '2026-09-01',
  },
  {
    id: 'LAP-2026-09-007',
    mitraId: 'MO011',
    namaSekolah: 'SMA Lazuardi',
    bulan: 'September',
    tahun: 2026,
    tahunAjaran: '2026/2027',
    tanggalKirim: '2026-09-14',
    kategori: 'Kesiswaan',
    ringkasan: 'Laporan pra-PTS dan pendaftaran delegasi olimpiade sains nasional serta festival budaya lintas negara.',
    kendala: 'Pengaturan waktu bimbingan intensif sore.',
    solusi: 'Menggunakan hybrid coaching online.',
    linkDokumen: 'https://docs.google.com/document/d/1lazuardi-sma-september-2026/edit',
    status: 'Diterima',
    catatanAdmin: 'Kepatuhan pelaporan sempurna (3 dari 3 bulan).',
    tanggalDiajukan: '2026-09-14',
  },
  {
    id: 'LAP-2026-08-005',
    mitraId: 'MO012',
    namaSekolah: 'Tursina Bandung',
    bulan: 'Juli',
    tahun: 2026,
    tahunAjaran: '2026/2027',
    tanggalKirim: '2026-08-06',
    kategori: 'Komprehensif',
    ringkasan: 'Kesiapan sarana asrama dan kelas boarding school, orientasi wali santri, dan pembagian wali kamar.',
    kendala: 'Kapasitas loker santri baru perlu penambahan.',
    solusi: 'Pengadaan mandiri oleh komite yayasan.',
    linkDokumen: 'https://docs.google.com/document/d/1lazuardi-tursina-juli-2026/edit',
    status: 'Diterima',
    catatanAdmin: 'Laporan awal tahun tuntas.',
    tanggalDiajukan: '2026-08-06',
  },
  {
    id: 'LAP-2026-09-008',
    mitraId: 'MO012',
    namaSekolah: 'Tursina Bandung',
    bulan: 'Agustus',
    tahun: 2026,
    tahunAjaran: '2026/2027',
    tanggalKirim: '2026-09-04',
    kategori: 'SDM & Operasional',
    ringkasan: 'Audit kebersihan dapur asrama, pembinaan adab santri, dan pelaksanaan program tadarus harian.',
    kendala: 'Kebutuhan pelatihan pengasuh asrama malam.',
    solusi: 'Mengikuti sesi upgrading dari Mitra Office.',
    linkDokumen: 'https://docs.google.com/document/d/1lazuardi-tursina-agustus-2026/edit',
    status: 'Diterima',
    catatanAdmin: 'Disetujui tanpa catatan khusus.',
    tanggalDiajukan: '2026-09-04',
  },
  {
    id: 'LAP-2026-08-006',
    mitraId: 'MO007',
    namaSekolah: 'Haura',
    bulan: 'Juli',
    tahun: 2026,
    tahunAjaran: '2026/2027',
    tanggalKirim: '2026-08-10',
    kategori: 'Komprehensif',
    ringkasan: 'Laporan MPLS pra-TK dan SD, penataan ruang terapi sensorik integrasi untuk siswa berkebutuhan khusus.',
    kendala: 'Perbaikan pendingin udara di ruang terapi anak.',
    solusi: 'Servis teknisi lokal selesai tanggal 28 Juli.',
    linkDokumen: 'https://docs.google.com/document/d/1lazuardi-haura-juli-2026/edit',
    status: 'Diterima',
    catatanAdmin: 'Laporan diterima.',
    tanggalDiajukan: '2026-08-10',
  },
  {
    id: 'LAP-2026-09-009',
    mitraId: 'MO010',
    namaSekolah: 'Kamila',
    bulan: 'Agustus',
    tahun: 2026,
    tahunAjaran: '2026/2027',
    tanggalKirim: '2026-09-04',
    kategori: 'Komprehensif',
    ringkasan: 'Pelaksanaan Gebyar Kemerdekaan, peresmian pojok baca ramah anak, dan parenting class tema Compassionate Family.',
    kendala: 'Laporan bulan Juli terlewat karena pergantian kepala tata usaha.',
    solusi: 'Akan segera menyusulkan rekap bulan Juli.',
    linkDokumen: 'https://docs.google.com/document/d/1lazuardi-kamila-agustus-2026/edit',
    status: 'Diterima',
    catatanAdmin: 'Segera susulkan laporan bulan Juli.',
    tanggalDiajukan: '2026-09-04',
  },
];

export const INITIAL_INVOICES: Invoice[] = processedHistorical.invoices;

export const INITIAL_PEMBAYARAN: Pembayaran[] = processedHistorical.pembayaran;

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'EVT-01',
    judul: 'Workshop Penguatan Kurikulum MenDAKI 2026',
    kategori: 'Workshop Kurikulum',
    tanggal: '2026-09-24',
    waktu: '08:30 - 15:30 WIB',
    lokasi: 'Auditorium Lazuardi Pusat, Cinere & Hybrid Zoom',
    pic: 'Anita Sulastri',
    mitraPeserta: 'Semua Sekolah Mitra & Afiliasi',
    status: 'Direncanakan',
    deskripsi: 'Bedah kurikulum MenDAKI pilar pembelajaran berbasis projek dan pembentukan karakter welas asih.',
    classroomUrl: 'https://classroom.google.com/c/NjkxOTI2Nzk4ODY5?cjc=ljp5l3k',
    classCode: 'ljp5l3k',
  },
  {
    id: 'EVT-02',
    judul: 'Pelatihan Guru Inklusi & Pembelajaran Diferensiasi',
    kategori: 'Pelatihan Guru',
    tanggal: '2026-09-30',
    waktu: '09:00 - 12:30 WIB',
    lokasi: 'Zoom Meeting Room Mitra Office',
    pic: 'Delfi Dwi Hermawati',
    mitraPeserta: 'Al-Falah Depok, Cordova, Ibnu Sina',
    status: 'Direncanakan',
    deskripsi: 'Strategi pendampingan anak berkebutuhan khusus (ABK) dan penyusunan IEP (Individualized Education Program).',
    classroomUrl: 'https://classroom.google.com/c/NjkxOTI2Nzk4ODY5?cjc=ljp5l3k',
    classCode: 'ljp5l3k',
  },
  {
    id: 'EVT-03',
    judul: 'Rapat Koordinasi Triwulan Pimpinan Sekolah Mitra',
    kategori: 'Koordinasi Pimpinan',
    tanggal: '2026-10-08',
    waktu: '13:00 - 16:00 WIB',
    lokasi: 'Hotel Santika Premiere Bintaro & Zoom',
    pic: 'Anita Sulastri',
    mitraPeserta: 'Semua Kepala Sekolah Mitra',
    status: 'Direncanakan',
    deskripsi: 'Evaluasi pencapaian semester berjalan, proyeksi SPMB 2027/2028, dan pembaharuan SOP.',
    classroomUrl: 'https://classroom.google.com/c/NjkxOTI2Nzk4ODY5?cjc=ljp5l3k',
    classCode: 'ljp5l3k',
  },
  {
    id: 'EVT-04',
    judul: 'Supervisi Mutu dan Audit Administrasi Semester 1',
    kategori: 'Supervisi Mutu',
    tanggal: '2026-09-18',
    waktu: '08:00 - 16:00 WIB',
    lokasi: 'Kampus Lazuardi Al-Falah Depok',
    pic: 'Delfi Dwi Hermawati',
    mitraPeserta: 'Al-Falah Depok',
    status: 'Berjalan',
    deskripsi: 'Audit lapangan kesesuaian SOP akademik, administrasi kesiswaan, dan tata kelola sarana.',
    classroomUrl: 'https://classroom.google.com/c/NjkxOTI2Nzk4ODY5?cjc=ljp5l3k',
    classCode: 'ljp5l3k',
  },
];

export const INITIAL_PERMINTAAN: PermintaanMitra[] = [
  {
    id: 'REQ-202609-001',
    mitraId: 'MO004',
    namaSekolah: 'Al-Falah Depok',
    kategori: 'Seragam',
    itemDetail: 'Batik Khas Lazuardi Siswa SD: Ukuran S (25 pcs), M (40 pcs), L (20 pcs). Kaos Olahraga: 50 pcs.',
    jumlah: 135,
    tanggalPengajuan: '2026-09-08',
    status: 'Diproses',
    noResi: 'JNE-TRK-9902189',
    estimasiSelesai: '2026-09-20',
    catatanAdmin: 'Sedang tahap finalisasi bordir logo di konveksi rekanan Mitra Office.',
  },
  {
    id: 'REQ-202609-002',
    mitraId: 'MO008',
    namaSekolah: 'Ibnu Sina',
    kategori: 'Dokumen Cetak',
    itemDetail: 'Buku Raport Karakter Compassionate School (Hardcover Emas): 150 buku, Buku Panduan Parent Handbook: 100 eksemplar.',
    jumlah: 250,
    tanggalPengajuan: '2026-09-06',
    status: 'Dikirim',
    noResi: 'TIKI-88129031',
    estimasiSelesai: '2026-09-17',
    catatanAdmin: 'Paket telah diserahkan ke kurir logistik hari ini.',
  },
  {
    id: 'REQ-202609-003',
    mitraId: 'MO006',
    namaSekolah: 'Cordova',
    kategori: 'Merchandise & Lainnya',
    itemDetail: 'Pin Akreditasi Guru Lazuardi: 40 pcs, Bendera Pataka Logo Lazuardi Besar: 2 unit.',
    jumlah: 42,
    tanggalPengajuan: '2026-09-12',
    status: 'Diajukan',
    catatanAdmin: 'Menunggu review ketersediaan stok di gudang logistik pusat.',
  },
  {
    id: 'REQ-202608-015',
    mitraId: 'MO011',
    namaSekolah: 'SMA Lazuardi',
    kategori: 'Dokumen Cetak',
    itemDetail: 'Ijazah & Transkrip Blanko Khusus Lazuardi Foundation: 90 lembar.',
    jumlah: 90,
    tanggalPengajuan: '2026-08-20',
    status: 'Selesai',
    noResi: 'INTERNAL-COURIER-04',
    estimasiSelesai: '2026-08-25',
    catatanAdmin: 'Telah diterima langsung oleh Bagian TU SMA Lazuardi.',
  },
];

export const INITIAL_STAFF_ACTIVITY: StaffActivity[] = [
  {
    id: 'ACT-01',
    noKpi: 'KPI-01',
    penjelasanKpi: 'Tercapainya kesiapan kurikulum MenDAKI dan supervisi modul pembelajaran minimal 90% pada periode berjalan',
    namaStaff: 'Delfi Dwi Hermawati',
    tugas: 'Supervisi Lapangan Kesiapan Pembelajaran MenDAKI',
    judulAktivitas: 'Supervisi Lapangan Kesiapan Pembelajaran MenDAKI',
    programKpi: 'Supervisi & Pendampingan Kurikulum/MenDAKI',
    tahunAjaran: '2026/2027',
    tanggal: '2026-09-14',
    deadline: '2026-09-18',
    jamMulai: '08:30',
    jamSelesai: '14:00',
    bobotKpi: 25,
    kpiScore: 25,
    hasilCatatan: 'Observasi kelas 1-3 SD, fasilitas sentra belajar terawat dengan baik, administrasi RPP berbasis modul Lazuardi sudah 92% terpenuhi.',
    catatanTindakLanjut: 'Kirimkan modul suplemen literasi digital ke Wakakurikulum.',
    googleCalendarSynced: true,
    status: 'Sedang Berjalan',
  },
  {
    id: 'ACT-02',
    noKpi: 'KPI-02',
    penjelasanKpi: 'Kelengkapan kepatuhan lisensi, kelayakan legalitas jenjang baru dan ketepatan pembayaran termin',
    namaStaff: 'Anita Sulastri',
    tugas: 'Audit Kepatuhan Lisensi & Pembahasan Rencana Jenjang Baru',
    judulAktivitas: 'Audit Kepatuhan Lisensi & Pembahasan Rencana Jenjang Baru',
    programKpi: 'Audit Lisensi, Kepatuhan & Keuangan Mitra',
    tahunAjaran: '2026/2027',
    tanggal: '2026-09-16',
    deadline: '2026-09-22',
    jamMulai: '10:00',
    jamSelesai: '15:30',
    bobotKpi: 30,
    hasilCatatan: 'Koordinasi bersama pengurus yayasan terkait penambahan jenjang SMP dan pelunasan fee termin.',
    catatanTindakLanjut: 'Draft MoU perpanjangan lisensi disiapkan tim legal.',
    googleCalendarSynced: true,
    status: 'Belum Dimulai',
  },
  {
    id: 'ACT-03',
    noKpi: 'KPI-01',
    penjelasanKpi: 'Pendampingan implementasi modul inklusi dan efektivitas pembinaan shadow teacher di sekolah mitra',
    namaStaff: 'Delfi Dwi Hermawati',
    tugas: 'Pendampingan Kurikulum Inklusi & Konsultasi Shadow Teacher',
    judulAktivitas: 'Pendampingan Kurikulum Inklusi & Konsultasi Shadow Teacher',
    programKpi: 'Supervisi & Pendampingan Kurikulum/MenDAKI',
    tahunAjaran: '2026/2027',
    tanggal: '2026-09-10',
    deadline: '2026-09-12',
    jamMulai: '13:00',
    jamSelesai: '16:00',
    bobotKpi: 20,
    kpiScore: 20,
    hasilCatatan: 'Telah disepakati 4 rekomendasi penanganan siswa berkebutuhan khusus dengan modul adaptif.',
    catatanTindakLanjut: 'Monitoring evaluasi IEP pada minggu ke-4.',
    googleCalendarSynced: true,
    status: 'Selesai',
  },
  {
    id: 'ACT-04',
    noKpi: 'KPI-08',
    penjelasanKpi: 'Kelancaran koordinasi internal Mitra Office dan ketepatan evaluasi berkala operasional bulanan',
    namaStaff: 'Anita Sulastri',
    tugas: 'Internal Briefing Mitra Office Evaluasi Bulanan',
    judulAktivitas: 'Internal Briefing Mitra Office Evaluasi Bulanan',
    programKpi: 'Operasional Internal & Koordinasi Mitra Office',
    tahunAjaran: '2026/2027',
    tanggal: '2026-09-12',
    deadline: '2026-09-15',
    jamMulai: '09:00',
    jamSelesai: '11:00',
    bobotKpi: 25,
    kpiScore: 25,
    hasilCatatan: 'Monitoring progres tagihan renewal fee dan kesiapan peluncuran portal digital L-MAP.',
    catatanTindakLanjut: 'Kirim notulen hasil rapat evaluasi ke seluruh manajemen.',
    googleCalendarSynced: true,
    status: 'Selesai',
  },
  {
    id: 'ACT-05',
    noKpi: 'KPI-06',
    penjelasanKpi: 'Ketepatan verifikasi laporan bulanan dan rekonsiliasi data enrollment serta keuangan mitra',
    namaStaff: 'Delfi Dwi Hermawati',
    tugas: 'Verifikasi Laporan Bulanan & Validasi Rekap Keuangan Mitra',
    judulAktivitas: 'Verifikasi Laporan Bulanan & Validasi Rekap Keuangan Mitra',
    programKpi: 'Evaluasi Kinerja, Rekapitulasi & Pelaporan Bulanan',
    tahunAjaran: '2026/2027',
    tanggal: '2026-09-15',
    deadline: '2026-09-20',
    jamMulai: '09:00',
    jamSelesai: '12:00',
    bobotKpi: 20,
    kpiScore: 18,
    hasilCatatan: 'Data enrollment siswa baru sudah diverifikasi dan sinkron dengan sistem penerimaan fee.',
    catatanTindakLanjut: 'Terbitkan surat tanda terima laporan resmi.',
    googleCalendarSynced: true,
    status: 'Sedang Berjalan',
  },
  {
    id: 'ACT-06',
    noKpi: 'KPI-03',
    penjelasanKpi: 'Peningkatan kompetensi guru inklusi melalui pelatihan kurikulum berdiferensiasi dan sertifikasi mutu',
    namaStaff: 'Anita Sulastri',
    tugas: 'Workshop Kurikulum Berdiferensiasi Guru Inklusi',
    judulAktivitas: 'Workshop Kurikulum Berdiferensiasi Guru Inklusi',
    programKpi: 'Pelatihan & Peningkatan Mutu SDM / Guru Inklusi',
    tahunAjaran: '2026/2027',
    tanggal: '2026-09-23',
    deadline: '2026-09-25',
    jamMulai: '08:30',
    jamSelesai: '15:00',
    bobotKpi: 25,
    hasilCatatan: 'Pelatihan 24 guru pengampu mata pelajaran intrakulikuler dan guru pembimbing khusus.',
    catatanTindakLanjut: 'Distribusi materi sertifikat kehadiran.',
    googleCalendarSynced: false,
    status: 'Belum Dimulai',
  },
];

export const INITIAL_TEMPLATES: TemplateDokumen[] = [
  {
    id: 'TMP-01',
    judul: 'Format Laporan Bulanan Resmi Sekolah Mitra 2026',
    kategori: 'Laporan Bulanan',
    deskripsi: 'Template Google Docs / Sheets resmi untuk pelaporan berkala akademik, kesiswaan, dan operasional ke Mitra Office.',
    linkUrl: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/template/preview',
    format: 'DOCX',
    versi: 'v3.2 - 2026',
  },
  {
    id: 'TMP-02',
    judul: 'SOP Pembukaan & Penambahan Jenjang Baru Mitra',
    kategori: 'SOP',
    deskripsi: 'Standar Operasional Prosedur penambahan jenjang pendidikan, visitasi kelayakan, dan persyaratan administrasi.',
    linkUrl: 'https://drive.google.com/file/d/1SOP-Jenjang-Baru-Lazuardi/view',
    format: 'PDF',
    versi: 'v2.0',
  },
  {
    id: 'TMP-03',
    judul: 'Parent Handbook Lazuardi Compassionate School 2026/2027',
    kategori: 'Parent Handbook',
    deskripsi: 'Buku panduan resmi orang tua murid berisi filosofi compassionate, budaya sekolah, tata tertib, dan kalender pendidikan.',
    linkUrl: 'https://drive.google.com/file/d/1Parent-Handbook-Lazuardi/view',
    format: 'PDF',
    versi: 'v4.1 - 2026',
  },
  {
    id: 'TMP-04',
    judul: 'Video Panduan Administrasi & Penggunaan Portal L-MAP',
    kategori: 'Video Panduan',
    deskripsi: 'Tutorial video langkah demi langkah pengisian laporan bulanan, permohonan logistik, dan konfirmasi bukti transfer di L-MAP.',
    linkUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    format: 'VIDEO',
    versi: 'HD Tutorial',
  },
  {
    id: 'TMP-05',
    judul: 'Modul Implementasi Kerangka Penilaian MenDAKI',
    kategori: 'Kurikulum & Modul',
    deskripsi: 'Panduan instrumen penilaian 5 pilar MenDAKI beserta rubrik pembinaan dan kriteria capaian predikat sekolah unggul.',
    linkUrl: 'https://drive.google.com/file/d/1MenDAKI-Framework-Guide/view',
    format: 'PDF',
    versi: 'v2.5',
  },
  {
    id: 'TMP-06',
    judul: 'Template Perjanjian Kerjasama (PKS) & Kontrak Lisensi',
    kategori: 'Legal & Kontrak',
    deskripsi: 'Draft kontrak resmi perpanjangan masa kerjasama (Renewal) dan hak cipta kurikulum Lazuardi.',
    linkUrl: 'https://docs.google.com/document/d/1PKS-Lazuardi-Mitra/view',
    format: 'DOCX',
    versi: 'v2026-Rev',
  },
];

export const INITIAL_PERFORMANCE_MENDAKI: PerformanceMenDAKI[] = [
  {
    id: 'MDK-01',
    mitraId: 'MO004',
    namaSekolah: 'Al-Falah Depok',
    periode: 'Semester Genap 2025/2026',
    skorManajemen: 92,
    skorKurikulum: 95,
    skorSDM: 88,
    skorKemitraan: 94,
    skorBranding: 90,
    totalSkor: 91.8,
    predikat: 'Sangat Memuaskan (A)',
    catatanRekomendasi: 'Mempertahankan konsistensi implementasi kurikulum compassionate. Perlu penguatan regenerasi koordinator jenjang SMP.',
    tanggalPenilaian: '2026-07-20',
  },
  {
    id: 'MDK-02',
    mitraId: 'MO006',
    namaSekolah: 'Cordova',
    periode: 'Semester Genap 2025/2026',
    skorManajemen: 86,
    skorKurikulum: 89,
    skorSDM: 84,
    skorKemitraan: 88,
    skorBranding: 85,
    totalSkor: 86.4,
    predikat: 'Memuaskan (B)',
    catatanRekomendasi: 'Peningkatan keterlibatan orang tua dalam Parenting Compassionate Day dan penyusunan portofolio digital siswa.',
    tanggalPenilaian: '2026-07-22',
  },
  {
    id: 'MDK-03',
    mitraId: 'MO008',
    namaSekolah: 'Ibnu Sina',
    periode: 'Semester Genap 2025/2026',
    skorManajemen: 90,
    skorKurikulum: 92,
    skorSDM: 89,
    skorKemitraan: 90,
    skorBranding: 92,
    totalSkor: 90.6,
    predikat: 'Sangat Memuaskan (A)',
    catatanRekomendasi: 'Pengelolaan branding dan media sosial sangat aktif. Rekomendasi menjadi sekolah rujukan studi tiru mitra baru.',
    tanggalPenilaian: '2026-07-25',
  },
  {
    id: 'MDK-04',
    mitraId: 'MO005',
    namaSekolah: 'Al-Falah Klaten',
    periode: 'Semester Genap 2025/2026',
    skorManajemen: 78,
    skorKurikulum: 82,
    skorSDM: 76,
    skorKemitraan: 80,
    skorBranding: 74,
    totalSkor: 78.0,
    predikat: 'Cukup (C)',
    catatanRekomendasi: 'Perlu bimbingan intensif penyusunan instrumen evaluasi pembelajaran mandiri dan percepatan digitalisasi administrasi.',
    tanggalPenilaian: '2026-07-28',
  },
  {
    id: 'MDK-05',
    mitraId: 'MO011',
    namaSekolah: 'SMA Lazuardi',
    periode: 'Semester Genap 2025/2026',
    skorManajemen: 94,
    skorKurikulum: 96,
    skorSDM: 93,
    skorKemitraan: 95,
    skorBranding: 95,
    totalSkor: 94.6,
    predikat: 'Sangat Memuaskan (A)',
    catatanRekomendasi: 'Benchmark unggulan untuk program Global Citizenship dan penyerapan lulusan ke perguruan tinggi top nasional dan dunia.',
    tanggalPenilaian: '2026-07-18',
  },
];
